# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build App
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifacts@v2
        with:
          name: whiteboard-app
          path: build/

  release:
    name: Release whiteboard app to Github Releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download published artifact
        uses: actions/download-artifact@v2
        with:
          name: whiteboard-app

      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: avd-dev-white-board-app.zip

      - name: Create Github Release
        id: create-new-github-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}

      - name: Upload asset to GitHub Releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-github-release.outputs.upload_url }}
          asset_path: ./avd-dev-white-board-app.zip
          asset_name: avbd-wb-app-v${{ github.run_number }}.zip
          asset_content_type: application/zip
